nicole-james-ahmed-hash-challenges
learn-academy-2022-delta/ruby-challenges pull request #28
Opened 2022-07-11 17:48 UTC by Ahmedkhafaji

2022-07-12 17:08 UTC, elysemontano requested changes
You may want to remove the interview file.

2022-07-12 23:57 UTC, elysemontano requested changes
Could you remove the interview file in this PR?

2022-07-13 19:11 UTC, Ahmedkhafaji commented
I still want to finish it up to get some practice in! it barely has anything sadly :(

2022-07-13 23:21 UTC, elysemontano approved these changes

2022-07-14 18:20 UTC, merged